inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1

Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario']
Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'
Style/Documentation:
  Enabled: false
